### ISSUE TITLE
Ignore Dependabot types- patch updates

### ISSUE THREAD

**Issue by josh** [josh/us-state-travel-advisories-feeds#6]
```yaml
ignore:
 - dependency-name: "types-*"
   update-types: ["version-update:semver-patch"]
```
